import type { Match } from "./types";

export const matches: Match[] = [
  // ─── Excellent (90+) ────────────────────────────────────────────────────────
  {
    id: "m1",
    candidate: {
      id: "savannah-nguyen",
      name: "Savannah Nguyen",
      initials: "SN",
      avatarColor: "#857B6C",
      role: "Senior Product Designer",
      location: "Toronto, Canada",
      experienceYears: 5,
      experienceLabel: "5y exp",
      seniority: "Senior",
      verified: true,
    },
    job: {
      id: "j1",
      title: "Senior Product Designer",
      company: "Shopify",
      companyLogoText: "S",
      companyLogoColor: "#96BF48",
      location: "Toronto, Canada",
      workMode: "Hybrid",
      salaryMin: 120_000,
      salaryMax: 160_000,
      salaryLabel: "$120K – $160K",
      applicants: 45,
      postedAgo: "2d ago",
      source: "Shopify Careers",
    },
    score: 93,
    quality: "Excellent",
    fitBreakdown: { skills: 95, location: 100, seniority: 92, salary: 85 },
    matchedSkills: ["Figma", "UI/UX", "Design Systems", "Prototyping", "User Research"],
    missingSkills: ["Webflow"],
    whyMatch: [
      "Skills match 95% of job requirements",
      "Location is an exact match — Toronto, Canada",
      "5+ years experience meets the seniority level",
    ],
    saved: false,
  },
  {
    id: "m2",
    candidate: {
      id: "jane-cooper",
      name: "Jane Cooper",
      initials: "JC",
      avatarColor: "#9A9183",
      role: "Senior Backend Engineer",
      location: "San Francisco, CA",
      experienceYears: 5,
      experienceLabel: "5y exp",
      seniority: "Senior",
      verified: true,
    },
    job: {
      id: "j2",
      title: "Senior Backend Engineer",
      company: "Stripe",
      companyLogoText: "S",
      companyLogoColor: "#EA6814",
      location: "San Francisco, CA",
      workMode: "Hybrid",
      salaryMin: 145_000,
      salaryMax: 185_000,
      salaryLabel: "$145K – $185K",
      applicants: 60,
      postedAgo: "1w ago",
      source: "Stripe Careers",
    },
    score: 91,
    quality: "Excellent",
    fitBreakdown: { skills: 95, location: 100, seniority: 92, salary: 78 },
    matchedSkills: ["Node.js", "PostgreSQL", "GraphQL", "TypeScript"],
    missingSkills: ["Ruby", "Kafka"],
    whyMatch: [
      "Node.js and PostgreSQL expertise is an excellent match",
      "Location is an exact match — San Francisco, CA",
      "GraphQL experience is a valuable bonus skill",
    ],
    saved: false,
  },
  {
    id: "m3",
    candidate: {
      id: "brooklyn-simmons",
      name: "Brooklyn Simmons",
      initials: "BS",
      avatarColor: "#8E726B",
      role: "Senior Mobile Engineer",
      location: "Remote · US",
      experienceYears: 6,
      experienceLabel: "6y exp",
      seniority: "Senior",
      verified: true,
    },
    job: {
      id: "j3",
      title: "Staff iOS Engineer",
      company: "Linear",
      companyLogoText: "L",
      companyLogoColor: "#ED8E55",
      location: "Remote",
      workMode: "Remote",
      salaryMin: 165_000,
      salaryMax: 210_000,
      salaryLabel: "$165K – $210K",
      applicants: 38,
      postedAgo: "3d ago",
      source: "Linear",
    },
    score: 94,
    quality: "Excellent",
    fitBreakdown: { skills: 100, location: 100, seniority: 88, salary: 88 },
    matchedSkills: ["Swift", "SwiftUI", "Combine", "iOS", "Objective-C"],
    missingSkills: [],
    whyMatch: [
      "Strong Swift / SwiftUI background — every required skill present",
      "Remote alignment is perfect",
      "Slightly below Staff level on paper, but trajectory is strong",
    ],
    saved: false,
  },
  {
    id: "m4",
    candidate: {
      id: "wade-warren",
      name: "Wade Warren",
      initials: "WW",
      avatarColor: "#9A9183",
      role: "Staff Software Engineer",
      location: "Denver, CO",
      experienceYears: 8,
      experienceLabel: "8y exp",
      seniority: "Lead",
      verified: true,
    },
    job: {
      id: "j4",
      title: "Staff Engineer, Platform",
      company: "Vercel",
      companyLogoText: "▲",
      companyLogoColor: "#000000",
      location: "Remote · US",
      workMode: "Remote",
      salaryMin: 190_000,
      salaryMax: 240_000,
      salaryLabel: "$190K – $240K",
      applicants: 27,
      postedAgo: "5d ago",
      source: "Vercel Careers",
    },
    score: 92,
    quality: "Excellent",
    fitBreakdown: { skills: 95, location: 100, seniority: 90, salary: 82 },
    matchedSkills: ["Next.js", "TypeScript", "Edge Compute", "Distributed Systems", "Postgres"],
    missingSkills: ["Rust"],
    whyMatch: [
      "Deep Next.js + edge platform experience",
      "Remote-first, time-zone friendly",
      "Lead-level scope already, ready to step into Staff",
    ],
    saved: true,
  },

  // ─── Good (75–89) ───────────────────────────────────────────────────────────
  {
    id: "m5",
    candidate: {
      id: "cameron-williamson",
      name: "Cameron Williamson",
      initials: "CW",
      avatarColor: "#9A9183",
      role: "Product Manager",
      location: "New York, NY",
      experienceYears: 4,
      experienceLabel: "4y exp",
      seniority: "Mid",
      verified: true,
    },
    job: {
      id: "j5",
      title: "Senior Product Manager",
      company: "Notion",
      companyLogoText: "N",
      companyLogoColor: "#000000",
      location: "New York, NY",
      workMode: "Hybrid",
      salaryMin: 150_000,
      salaryMax: 190_000,
      salaryLabel: "$150K – $190K",
      applicants: 72,
      postedAgo: "3d ago",
      source: "Notion",
    },
    score: 88,
    quality: "Good",
    fitBreakdown: { skills: 90, location: 100, seniority: 78, salary: 84 },
    matchedSkills: ["Product Strategy", "Analytics", "Roadmapping", "User Research"],
    missingSkills: ["B2B SaaS"],
    whyMatch: [
      "Strong product management background aligns perfectly",
      "Analytics expertise matches core job requirements",
      "Location is an exact match — New York, NY",
    ],
    saved: false,
  },
  {
    id: "m6",
    candidate: {
      id: "floyd-miles",
      name: "Floyd Miles",
      initials: "FM",
      avatarColor: "#9A9183",
      role: "Cloud Architect",
      location: "Chicago, IL",
      experienceYears: 8,
      experienceLabel: "8y exp",
      seniority: "Lead",
      verified: true,
    },
    job: {
      id: "j6",
      title: "Cloud Solutions Architect",
      company: "Microsoft",
      companyLogoText: "M",
      companyLogoColor: "#00A4EF",
      location: "Redmond, WA",
      workMode: "Hybrid",
      salaryMin: 155_000,
      salaryMax: 200_000,
      salaryLabel: "$155K – $200K",
      applicants: 51,
      postedAgo: "2d ago",
      source: "Microsoft Careers",
    },
    score: 87,
    quality: "Good",
    fitBreakdown: { skills: 95, location: 65, seniority: 100, salary: 88 },
    matchedSkills: ["Azure", "AWS", "Terraform", "Kubernetes"],
    missingSkills: ["Bicep"],
    whyMatch: [
      "Azure expertise is a direct and perfect match",
      "8+ years experience comfortably meets architect requirements",
      "Relocation or remote arrangement needed",
    ],
    saved: false,
  },
  {
    id: "m7",
    candidate: {
      id: "robert-fox",
      name: "Robert Fox",
      initials: "RF",
      avatarColor: "#9A9183",
      role: "DevOps Engineer",
      location: "Dallas, TX",
      experienceYears: 6,
      experienceLabel: "6y exp",
      seniority: "Senior",
      verified: true,
    },
    job: {
      id: "j7",
      title: "Senior DevOps Engineer",
      company: "Ramp",
      companyLogoText: "R",
      companyLogoColor: "#F0EFEA",
      location: "New York, NY",
      workMode: "Hybrid",
      salaryMin: 150_000,
      salaryMax: 195_000,
      salaryLabel: "$150K – $195K",
      applicants: 33,
      postedAgo: "4d ago",
      source: "Ramp Careers",
    },
    score: 84,
    quality: "Good",
    fitBreakdown: { skills: 95, location: 60, seniority: 95, salary: 86 },
    matchedSkills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    missingSkills: ["Datadog", "ArgoCD"],
    whyMatch: [
      "AWS / Docker / Kubernetes is a direct match",
      "Senior level fits the role exactly",
      "Location requires a hybrid arrangement",
    ],
    saved: true,
  },
  {
    id: "m8",
    candidate: {
      id: "kathryn-murphy",
      name: "Kathryn Murphy",
      initials: "KM",
      avatarColor: "#857B6C",
      role: "Data Scientist",
      location: "Austin, TX",
      experienceYears: 5,
      experienceLabel: "5y exp",
      seniority: "Senior",
      verified: true,
    },
    job: {
      id: "j8",
      title: "Senior ML Engineer",
      company: "Anthropic",
      companyLogoText: "A",
      companyLogoColor: "#D97757",
      location: "Remote · US",
      workMode: "Remote",
      salaryMin: 170_000,
      salaryMax: 210_000,
      salaryLabel: "$170K – $210K",
      applicants: 89,
      postedAgo: "1w ago",
      source: "Anthropic",
    },
    score: 82,
    quality: "Good",
    fitBreakdown: { skills: 88, location: 100, seniority: 85, salary: 56 },
    matchedSkills: ["Python", "PyTorch", "ML", "TensorFlow"],
    missingSkills: ["LLMs", "RLHF"],
    whyMatch: [
      "Strong Python + ML foundation transfers to LLM work",
      "Remote alignment is perfect",
      "Salary range may need negotiation",
    ],
    saved: false,
  },
  {
    id: "m9",
    candidate: {
      id: "esther-howard",
      name: "Esther Howard",
      initials: "EH",
      avatarColor: "#A89B82",
      role: "UX Researcher",
      location: "Austin, TX",
      experienceYears: 4,
      experienceLabel: "4y exp",
      seniority: "Mid",
      verified: true,
    },
    job: {
      id: "j9",
      title: "UX Researcher",
      company: "Figma",
      companyLogoText: "F",
      companyLogoColor: "#F24E1E",
      location: "San Francisco, CA",
      workMode: "Hybrid",
      salaryMin: 130_000,
      salaryMax: 165_000,
      salaryLabel: "$130K – $165K",
      applicants: 47,
      postedAgo: "5d ago",
      source: "Figma Careers",
    },
    score: 78,
    quality: "Good",
    fitBreakdown: { skills: 88, location: 55, seniority: 80, salary: 88 },
    matchedSkills: ["User Research", "Usability Testing", "Survey Design"],
    missingSkills: ["Quant Research"],
    whyMatch: [
      "Research skills cover 88% of the requirements",
      "Usability testing experience is a strong fit",
      "Location requires relocation or remote arrangement",
    ],
    saved: false,
  },
  {
    id: "m10",
    candidate: {
      id: "ralph-edwards",
      name: "Ralph Edwards",
      initials: "RE",
      avatarColor: "#9DA48A",
      role: "Frontend Developer",
      location: "Remote · US",
      experienceYears: 4,
      experienceLabel: "4y exp",
      seniority: "Mid",
      verified: true,
    },
    job: {
      id: "j10",
      title: "Senior Frontend Engineer",
      company: "Atlassian",
      companyLogoText: "A",
      companyLogoColor: "#0052CC",
      location: "Remote",
      workMode: "Remote",
      salaryMin: 130_000,
      salaryMax: 165_000,
      salaryLabel: "$130K – $165K",
      applicants: 54,
      postedAgo: "1w ago",
      source: "Atlassian",
    },
    score: 76,
    quality: "Good",
    fitBreakdown: { skills: 90, location: 100, seniority: 60, salary: 55 },
    matchedSkills: ["React", "TypeScript", "JavaScript", "Tailwind"],
    missingSkills: ["GraphQL", "Testing Library"],
    whyMatch: [
      "React and TypeScript skills align well with requirements",
      "Remote role matches candidate's working preference",
      "Experience slightly below the senior-level requirement",
    ],
    saved: false,
  },

  // ─── Fair (<75) ─────────────────────────────────────────────────────────────
  {
    id: "m11",
    candidate: {
      id: "marvin-mckinney",
      name: "Marvin McKinney",
      initials: "MM",
      avatarColor: "#9A9183",
      role: "Full Stack Developer",
      location: "New York, NY",
      experienceYears: 5,
      experienceLabel: "5y exp",
      seniority: "Mid",
      verified: true,
    },
    job: {
      id: "j11",
      title: "Senior Full Stack Engineer",
      company: "Airbnb",
      companyLogoText: "A",
      companyLogoColor: "#FF5A5F",
      location: "San Francisco, CA",
      workMode: "On-site",
      salaryMin: 150_000,
      salaryMax: 190_000,
      salaryLabel: "$150K – $190K",
      applicants: 91,
      postedAgo: "3d ago",
      source: "Airbnb Careers",
    },
    score: 72,
    quality: "Fair",
    fitBreakdown: { skills: 80, location: 30, seniority: 75, salary: 80 },
    matchedSkills: ["Python", "AWS", "Django"],
    missingSkills: ["React", "Ruby on Rails", "GraphQL"],
    whyMatch: [
      "Backend stack overlaps but frontend gap is real",
      "On-site location is a major blocker",
      "Senior level may require ramp-up time",
    ],
    saved: true,
  },
  {
    id: "m12",
    candidate: {
      id: "theresa-webb",
      name: "Theresa Webb",
      initials: "TW",
      avatarColor: "#9A9183",
      role: "Senior Designer",
      location: "Portland, OR",
      experienceYears: 6,
      experienceLabel: "6y exp",
      seniority: "Senior",
      verified: false,
    },
    job: {
      id: "j12",
      title: "Senior Brand Designer",
      company: "Figma",
      companyLogoText: "F",
      companyLogoColor: "#F24E1E",
      location: "San Francisco, CA",
      workMode: "Hybrid",
      salaryMin: 140_000,
      salaryMax: 175_000,
      salaryLabel: "$140K – $175K",
      applicants: 64,
      postedAgo: "2w ago",
      source: "Figma Careers",
    },
    score: 70,
    quality: "Fair",
    fitBreakdown: { skills: 75, location: 55, seniority: 95, salary: 55 },
    matchedSkills: ["Figma", "Brand Design", "Typography"],
    missingSkills: ["Motion", "Illustration"],
    whyMatch: [
      "Strong brand foundation but motion gap",
      "Hybrid role requires relocation",
      "Salary expectations may need calibration",
    ],
    saved: false,
  },
  {
    id: "m13",
    candidate: {
      id: "dianne-russell",
      name: "Dianne Russell",
      initials: "DR",
      avatarColor: "#9A6F66",
      role: "Marketing Specialist",
      location: "Chicago, IL",
      experienceYears: 3,
      experienceLabel: "3y exp",
      seniority: "Mid",
    },
    job: {
      id: "j13",
      title: "Senior Growth Marketing Manager",
      company: "Notion",
      companyLogoText: "N",
      companyLogoColor: "#000000",
      location: "San Francisco, CA",
      workMode: "Hybrid",
      salaryMin: 150_000,
      salaryMax: 190_000,
      salaryLabel: "$150K – $190K",
      applicants: 102,
      postedAgo: "1w ago",
      source: "Notion",
    },
    score: 65,
    quality: "Fair",
    fitBreakdown: { skills: 70, location: 30, seniority: 65, salary: 95 },
    matchedSkills: ["SEO", "Analytics", "Content Strategy"],
    missingSkills: ["Paid Acquisition", "Lifecycle Marketing", "Mixpanel"],
    whyMatch: [
      "SEO and analytics skills partially match requirements",
      "Location requires relocation or remote arrangement",
      "Growth focus area requires ramp-up time",
    ],
    saved: false,
  },
  {
    id: "m14",
    candidate: {
      id: "cody-fisher",
      name: "Cody Fisher",
      initials: "CF",
      avatarColor: "#A89B82",
      role: "Backend Engineer",
      location: "Boston, MA",
      experienceYears: 3,
      experienceLabel: "3y exp",
      seniority: "Mid",
      verified: true,
    },
    job: {
      id: "j14",
      title: "Staff Backend Engineer",
      company: "Ramp",
      companyLogoText: "R",
      companyLogoColor: "#F4F4F0",
      location: "New York, NY",
      workMode: "On-site",
      salaryMin: 200_000,
      salaryMax: 250_000,
      salaryLabel: "$200K – $250K",
      applicants: 28,
      postedAgo: "1d ago",
      source: "Ramp Careers",
    },
    score: 67,
    quality: "Fair",
    fitBreakdown: { skills: 80, location: 70, seniority: 50, salary: 65 },
    matchedSkills: ["Go", "Postgres", "AWS"],
    missingSkills: ["Distributed Systems", "Performance Tuning"],
    whyMatch: [
      "Strong fundamentals but Staff scope is a stretch",
      "On-site / NY requires relocation",
      "Salary band assumes more years than candidate has",
    ],
    saved: false,
  },
  {
    id: "m15",
    candidate: {
      id: "bessie-cooper",
      name: "Bessie Cooper",
      initials: "BC",
      avatarColor: "#9A9183",
      role: "Business Analyst",
      location: "Atlanta, GA",
      experienceYears: 4,
      experienceLabel: "4y exp",
      seniority: "Mid",
    },
    job: {
      id: "j15",
      title: "Senior Operations Analyst",
      company: "Shopify",
      companyLogoText: "S",
      companyLogoColor: "#96BF48",
      location: "Remote · US",
      workMode: "Remote",
      salaryMin: 110_000,
      salaryMax: 140_000,
      salaryLabel: "$110K – $140K",
      applicants: 119,
      postedAgo: "2w ago",
      source: "Shopify Careers",
    },
    score: 71,
    quality: "Fair",
    fitBreakdown: { skills: 70, location: 100, seniority: 70, salary: 60 },
    matchedSkills: ["SQL", "Excel", "Tableau"],
    missingSkills: ["Looker", "dbt", "Python"],
    whyMatch: [
      "Strong analytical foundation but tooling gap",
      "Remote alignment is perfect",
      "Salary may sit above the band's midpoint",
    ],
    saved: false,
  },
];

// Top skills derived from the dataset (used by the skills filter)
export const topSkills: string[] = (() => {
  const counts = new Map<string, number>();
  for (const m of matches) {
    for (const s of [...m.matchedSkills, ...m.missingSkills]) {
      counts.set(s, (counts.get(s) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([s]) => s);
})();

export const allRoles: string[] = [...new Set(matches.map((m) => m.job.title))].sort();
export const allLocations: string[] = [...new Set(matches.map((m) => m.job.location))].sort();
