// ─── Company → domain lookup ──────────────────────────────────────────────────
// Maps the names we use in mock data to the domain companyenrich expects.
// For companies not in the map, we fall back to a slugified "<name>.com" guess.

const DOMAIN_MAP: Record<string, string> = {
  // Tech / SaaS
  Stripe: "stripe.com",
  Shopify: "shopify.com",
  Linear: "linear.app",
  Figma: "figma.com",
  Notion: "notion.so",
  Vercel: "vercel.com",
  Anthropic: "anthropic.com",
  Ramp: "ramp.com",
  Atlassian: "atlassian.com",
  Microsoft: "microsoft.com",
  Airbnb: "airbnb.com",
  LinkedIn: "linkedin.com",
  Google: "google.com",
  Meta: "meta.com",
  Amazon: "amazon.com",
  Apple: "apple.com",
  Slack: "slack.com",
  Zoom: "zoom.us",
  Naukri: "naukri.com",
  Indeed: "indeed.com",
  Spotify: "spotify.com",
  Netflix: "netflix.com",
  Uber: "uber.com",
  Lyft: "lyft.com",
  Twitter: "twitter.com",
  X: "x.com",
  Discord: "discord.com",
  Coinbase: "coinbase.com",
  Reddit: "reddit.com",
  Pinterest: "pinterest.com",
  Snapchat: "snap.com",
  Snap: "snap.com",
  Tesla: "tesla.com",
  IBM: "ibm.com",
  Oracle: "oracle.com",
  Salesforce: "salesforce.com",
  Adobe: "adobe.com",
  Dropbox: "dropbox.com",
  Box: "box.com",
  Asana: "asana.com",
  ClickUp: "clickup.com",
  GitHub: "github.com",
  GitLab: "gitlab.com",
  Bitbucket: "bitbucket.org",
  Datadog: "datadoghq.com",
  "New Relic": "newrelic.com",
  PagerDuty: "pagerduty.com",
  Twilio: "twilio.com",
  SendGrid: "sendgrid.com",
  Mailchimp: "mailchimp.com",
  HubSpot: "hubspot.com",
  Zendesk: "zendesk.com",
  Intercom: "intercom.com",
  Segment: "segment.com",
  Mixpanel: "mixpanel.com",
  Amplitude: "amplitude.com",
  Snowflake: "snowflake.com",
  Databricks: "databricks.com",
  MongoDB: "mongodb.com",
  Redis: "redis.com",
  Elastic: "elastic.co",
  Cloudflare: "cloudflare.com",
  Fastly: "fastly.com",
  DigitalOcean: "digitalocean.com",
  "Google Calendar": "google.com",
  Gmail: "google.com",
  // Common alt aliases
  AWS: "aws.amazon.com",

  // ─── Design / creative tools ───────────────────────────────────────────────
  Sketch: "sketch.com",
  "Adobe XD": "adobe.com",
  Xd: "adobe.com",
  XD: "adobe.com",
  Photoshop: "adobe.com",
  Ps: "adobe.com",
  PS: "adobe.com",
  Illustrator: "adobe.com",
  Ai: "adobe.com",
  AI: "adobe.com",
  InDesign: "adobe.com",
  Id: "adobe.com",
  ID: "adobe.com",
  "After Effects": "adobe.com",
  Premiere: "adobe.com",
  "Adobe Creative Cloud": "adobe.com",
  InVision: "invisionapp.com",
  In: "invisionapp.com",
  Webflow: "webflow.com",
  Framer: "framer.com",
  Zeplin: "zeplin.io",
  Miro: "miro.com",
  Mural: "mural.co",
  Whimsical: "whimsical.com",
  Canva: "canva.com",
  ProtoPie: "protopie.io",
  Marvel: "marvelapp.com",
  Principle: "principleformac.com",
  Origami: "origami.design",
  "Lottie": "lottiefiles.com",

  // ─── Dev / tech ────────────────────────────────────────────────────────────
  React: "react.dev",
  "React Native": "reactnative.dev",
  Vue: "vuejs.org",
  "Vue.js": "vuejs.org",
  Angular: "angular.io",
  Svelte: "svelte.dev",
  "Next.js": "nextjs.org",
  Nuxt: "nuxt.com",
  TypeScript: "typescriptlang.org",
  JavaScript: "javascript.com",
  Python: "python.org",
  Django: "djangoproject.com",
  Flask: "flask.palletsprojects.com",
  Ruby: "ruby-lang.org",
  Rails: "rubyonrails.org",
  "Ruby on Rails": "rubyonrails.org",
  Go: "go.dev",
  Rust: "rust-lang.org",
  Java: "java.com",
  Kotlin: "kotlinlang.org",
  Swift: "swift.org",
  SwiftUI: "developer.apple.com",
  "Objective-C": "developer.apple.com",
  iOS: "developer.apple.com",
  Android: "android.com",
  PHP: "php.net",
  Laravel: "laravel.com",
  "Node.js": "nodejs.org",
  Deno: "deno.com",
  Bun: "bun.sh",
  Express: "expressjs.com",
  GraphQL: "graphql.org",
  PostgreSQL: "postgresql.org",
  Postgres: "postgresql.org",
  MySQL: "mysql.com",
  SQLite: "sqlite.org",
  Tailwind: "tailwindcss.com",
  "Tailwind CSS": "tailwindcss.com",
  Bootstrap: "getbootstrap.com",
  Sass: "sass-lang.com",
  SCSS: "sass-lang.com",
  Docker: "docker.com",
  Kubernetes: "kubernetes.io",
  Terraform: "terraform.io",
  Ansible: "ansible.com",
  Jenkins: "jenkins.io",
  CircleCI: "circleci.com",
  "GitHub Actions": "github.com",
  ArgoCD: "argo-cd.readthedocs.io",
  Azure: "azure.microsoft.com",
  GCP: "cloud.google.com",
  "Google Cloud": "cloud.google.com",
  Heroku: "heroku.com",
  Netlify: "netlify.com",
  Firebase: "firebase.google.com",
  Supabase: "supabase.com",
  Auth0: "auth0.com",
  PyTorch: "pytorch.org",
  TensorFlow: "tensorflow.org",
  Pandas: "pandas.pydata.org",
  NumPy: "numpy.org",
  Tableau: "tableau.com",
  Looker: "looker.com",
  PowerBI: "powerbi.microsoft.com",
  Excel: "microsoft.com",
  SQL: "microsoft.com",
  Jira: "atlassian.com",
  Confluence: "atlassian.com",
  Trello: "trello.com",
  Airtable: "airtable.com",
  "VS Code": "code.visualstudio.com",
  WebStorm: "jetbrains.com",
};

export function domainForCompany(name: string): string | null {
  if (!name) return null;
  const trimmed = name.trim();
  if (!trimmed) return null;
  if (DOMAIN_MAP[trimmed]) return DOMAIN_MAP[trimmed];
  // Slug fallback: "Acme Co." → "acmeco.com"
  const slug = trimmed.toLowerCase().replace(/[^a-z0-9]+/g, "");
  if (!slug) return null;
  // Skip obvious fake placeholders
  if (/^(techcorp|acme|example|sample|company|test|demo|client[abc])/i.test(slug)) return null;
  return `${slug}.com`;
}

export function logoUrl(domainOrCompany: string): string {
  // Accepts either a raw domain or a known company name and returns the
  // companyenrich logo CDN URL.
  const looksLikeDomain = /\./.test(domainOrCompany);
  const domain = looksLikeDomain
    ? domainOrCompany
    : (domainForCompany(domainOrCompany) ?? "");
  if (!domain) return "";
  return `https://api.companyenrich.com/logo/${encodeURIComponent(domain)}`;
}
